In [1]:
!pip install numpy

In [1]:
import numpy as np

In [3]:
sales = [10, 20, 30, 40]
type(sales)

list

In [4]:
target =[]
for i in sales:
    target.append(i*2)
print(target)

[20, 40, 60, 80]


In [5]:
arr = np.array(sales)
type(arr)

numpy.ndarray

In [7]:
double_sales=arr*2
double_sales

array([20, 40, 60, 80])

# creating a empty array

In [9]:
arr1=np.array([])
arr1

array([], dtype=float64)

In [16]:
my_list=[1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [12]:
arr2=np.array(my_list)
arr2

array([1, 2, 3, 4, 5])

In [13]:
arr2+[2]

array([3, 4, 5, 6, 7])

In [17]:
my_list+[2]

[1, 2, 3, 4, 5, 2]

# attributes:- its give information

In [20]:
arr2.ndim  #number of dimesinons in the array

1

In [21]:
arr2.size  #number of the elements

5

In [22]:
arr2.shape

(5,)

# arrays can be dimenisions

In [31]:
my_matrix=[[1,2,4,5,],[5,6,7,8],[7,8,5,2]]
my_matrix

[[1, 2, 4, 5], [5, 6, 7, 8], [7, 8, 5, 2]]

In [27]:
arr3=np.array(my_matrix)
arr3

array([[1, 2, 4, 5],
       [5, 6, 7, 8],
       [7, 8, 5, 2]])

In [28]:
arr3.ndim

2

In [29]:
arr3.size

12

In [30]:
arr3.shape

(3, 4)

In [34]:
arr3.dtype

dtype('int64')

In [55]:
arr4=np.array([[[1,2,3,],[4,5,6,]],[[7,8,9],[10,11,12]]])
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr4.ndim

3

In [48]:
arr4.size


12

In [49]:
arr4.shape

(1, 4, 3)

In [50]:
arr4.dtype

dtype('int64')

# Indexing and Slicing

In [59]:
arr4[1][0][2]

np.int64(9)

In [58]:
arr4[1][1][-1]

np.int64(12)

# **IN-BUILT FUNCTIONS**

## RESHAPE FUNCTION

In [71]:
arr5=np.array([[1,2,3,],[4,5,6]])
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
arr5.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [78]:
arr6=np.array([[[1,2,3,],[4,5,6],[7,8,9],[10,11,12]]])
arr6

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
print(arr6.dtype)
print(arr6.size)

int64
12


In [81]:
arr6.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [82]:
arr6.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [84]:
arr6.reshape(1,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [85]:
arr6.reshape(4,3,1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

# **arrange**

In [93]:
for i in range (1,10,2):   # in traditinal way using loop condition
    print(i)

1
3
5
7
9


In [99]:
np.arange(20) # it usinng arange function to genrate

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [103]:
np.arange(1,100,5) # last 5 is the interval

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [104]:
np.arange(1,100,5).reshape(2,10)

array([[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71, 76, 81, 86, 91, 96]])

## **zeros and ones**

In [ ]:
np.zeros(6)

In [108]:
np.zeros((3,2))  ## 2d array in zeros generate

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [109]:
np.zeros(((3,3,3)))  ## 3d arrays in zeros genrate

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [110]:
np.ones(6) ### number of element generate in ones

array([1., 1., 1., 1., 1., 1.])

In [111]:
np.ones((3,2)) ## 2d array in ones generate 

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [112]:
np.ones(((3,3,3))) ##3d array in ones genrate

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

## **linspace**

In [119]:
np.linspace(1,10000,20,retstep=True)

(array([1.00000000e+00, 5.27263158e+02, 1.05352632e+03, 1.57978947e+03,
        2.10605263e+03, 2.63231579e+03, 3.15857895e+03, 3.68484211e+03,
        4.21110526e+03, 4.73736842e+03, 5.26363158e+03, 5.78989474e+03,
        6.31615789e+03, 6.84242105e+03, 7.36868421e+03, 7.89494737e+03,
        8.42121053e+03, 8.94747368e+03, 9.47373684e+03, 1.00000000e+04]),
 np.float64(526.2631578947369))

In [120]:
np.linspace(1,10000,20,) #default 50 observation

array([1.00000000e+00, 5.27263158e+02, 1.05352632e+03, 1.57978947e+03,
       2.10605263e+03, 2.63231579e+03, 3.15857895e+03, 3.68484211e+03,
       4.21110526e+03, 4.73736842e+03, 5.26363158e+03, 5.78989474e+03,
       6.31615789e+03, 6.84242105e+03, 7.36868421e+03, 7.89494737e+03,
       8.42121053e+03, 8.94747368e+03, 9.47373684e+03, 1.00000000e+04])

# **EYE**

In [2]:
import numpy as np
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [3]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
np.eye(5,5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# **Broadcasting in an array**

methods  of accesing the each and every elements in array

In [7]:
arr7=np.arange(2,100,5)
arr7/6

array([ 0.33333333,  1.16666667,  2.        ,  2.83333333,  3.66666667,
        4.5       ,  5.33333333,  6.16666667,  7.        ,  7.83333333,
        8.66666667,  9.5       , 10.33333333, 11.16666667, 12.        ,
       12.83333333, 13.66666667, 14.5       , 15.33333333, 16.16666667])

In [8]:
arr7=np.arange(2,100,5)
arr7/6+6

array([ 6.33333333,  7.16666667,  8.        ,  8.83333333,  9.66666667,
       10.5       , 11.33333333, 12.16666667, 13.        , 13.83333333,
       14.66666667, 15.5       , 16.33333333, 17.16666667, 18.        ,
       18.83333333, 19.66666667, 20.5       , 21.33333333, 22.16666667])

In [10]:
arr7=np.arange(2,100,5)
arr7**3%5

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

# **Use of copy function**

In [12]:
arr8=np.arange(2,10)
arr8

array([2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b=arr8.copy()
b/5

array([0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

# **Random genration number**
Numpy also has lots way to create random genarate

## **randd**

In [45]:
np.random.rand(2)

array([0.56940025, 0.0887562 ])

In [17]:
np.random.rand(20)

array([0.79342436, 0.13428728, 0.61156845, 0.53513692, 0.8654119 ,
       0.59926612, 0.68445435, 0.13255529, 0.63833659, 0.50401699,
       0.84415712, 0.69249816, 0.28249852, 0.91472386, 0.86855723,
       0.46498146, 0.23206779, 0.70569341, 0.21902257, 0.05601521])

In [18]:
np.random.rand(5)

array([0.70529554, 0.95144833, 0.19479031, 0.44920644, 0.29540527])

In [21]:
np.random.rand(5,6) ##2d values genaration

array([[0.35755956, 0.38419163, 0.64717245, 0.85992751, 0.95922162,
        0.59458801],
       [0.29087294, 0.17405897, 0.72003272, 0.19763286, 0.62967679,
        0.81541521],
       [0.64603755, 0.26975078, 0.13259502, 0.37183751, 0.77213829,
        0.07128378],
       [0.03014328, 0.99471932, 0.44032513, 0.77941786, 0.71150328,
        0.37548693],
       [0.76512334, 0.29708791, 0.50535739, 0.04042504, 0.15741184,
        0.53666874]])

In [24]:
np.random.rand(5,5,5) ##3d array genration in random method

array([[[0.41363634, 0.64677296, 0.63327665, 0.34302384, 0.80961173],
        [0.83545955, 0.67472621, 0.5943799 , 0.08904767, 0.37802383],
        [0.64628033, 0.88640692, 0.09786454, 0.61201505, 0.44347624],
        [0.47429955, 0.03175533, 0.91126389, 0.33588526, 0.37644763],
        [0.36779092, 0.84656753, 0.19130759, 0.83448663, 0.22894258]],

       [[0.40520804, 0.02870562, 0.18258571, 0.63199469, 0.81290585],
        [0.81328589, 0.57841669, 0.64019554, 0.3329132 , 0.86405663],
        [0.15522924, 0.94538051, 0.14822941, 0.19984582, 0.4188275 ],
        [0.73919135, 0.36265146, 0.5275995 , 0.33986211, 0.0914177 ],
        [0.81002393, 0.78913361, 0.35909392, 0.98554542, 0.0889003 ]],

       [[0.13362331, 0.65571766, 0.38941794, 0.5819921 , 0.25108812],
        [0.61494801, 0.47958445, 0.16529361, 0.90316236, 0.86155906],
        [0.34313265, 0.43200574, 0.57299316, 0.54165679, 0.50816461],
        [0.81301058, 0.63517486, 0.11192154, 0.55543473, 0.95643085],
        [0.77060

# **randn :- Random normal distrbution functions genrate**

In [38]:
r1=np.random.randn(5)
r1

array([ 0.85604613,  0.91605973, -0.48070881,  0.5069207 ,  0.38563852])

In [43]:
np.mean(r1)

np.float64(0.43679125243314687)

In [44]:
np.median(r1)

np.float64(0.506920697051265)

In [42]:
np.std(r1)

np.float64(0.5009618797492641)

In [41]:
np.var(r1)

np.float64(0.2509628049619161)

# **randint:-Return random integers from low  and high**

In [46]:
np.random.randint(100,1000,10)

array([744, 575, 311, 228, 637, 434, 312, 674, 858, 699], dtype=int32)

In [51]:
np.random.randint(10,100,2)

array([83, 32], dtype=int32)

# **Array Attributes and methods**
let's discuss some useful attributes and methods or an array:

In [59]:
arr8=np.arange(100,900,8)
arr8

array([100, 108, 116, 124, 132, 140, 148, 156, 164, 172, 180, 188, 196,
       204, 212, 220, 228, 236, 244, 252, 260, 268, 276, 284, 292, 300,
       308, 316, 324, 332, 340, 348, 356, 364, 372, 380, 388, 396, 404,
       412, 420, 428, 436, 444, 452, 460, 468, 476, 484, 492, 500, 508,
       516, 524, 532, 540, 548, 556, 564, 572, 580, 588, 596, 604, 612,
       620, 628, 636, 644, 652, 660, 668, 676, 684, 692, 700, 708, 716,
       724, 732, 740, 748, 756, 764, 772, 780, 788, 796, 804, 812, 820,
       828, 836, 844, 852, 860, 868, 876, 884, 892])

In [57]:
arr8.min()

np.int64(100)

In [60]:
arr8.max()

np.int64(892)

In [61]:
print(arr8.argmin())

0


In [62]:
print(arr8.argmax())

99


In [71]:
l=[8,3,4,5,7,8,9]
l

[8, 3, 4, 5, 7, 8, 9]

In [72]:
arr9=np.array(l)
arr9

array([8, 3, 4, 5, 7, 8, 9])

In [73]:
print(arr9.min(),arr9.max(),arr9.argmin(),)

3 9 1


# **Matrix Transpose**

In [81]:
mat=np.arange(1,21).reshape(5,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [82]:
mat.T

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

In [83]:
np.transpose(mat)

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

In [85]:
mat=np.arange(1,10).reshape(3,3)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
mat.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# **Fancy Indexing**

fancy indexing allows you to select entire rows or columns out of order ,to showthis

In [3]:
import numpy as np

In [90]:
arr11=np.array([10,20,30,40,50])
sel=arr11[[0,4,3]]
sel

array([10, 50, 40])

In [91]:
arr12=np.arange(1,21).reshape(4,5)
arr12

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [95]:
arr12[0:3,[3,4]]

array([[ 4,  5],
       [ 9, 10],
       [14, 15]])

In [103]:
arr12[[0,3],0:3]

array([[ 1,  2,  3],
       [16, 17, 18]])

In [104]:
arr12[[0,3],[0]]

array([ 1, 16])

In [107]:
arr12.shape  ## its showing both rows and columns

(4, 5)

In [110]:
arr12.shape[0] 

4

In [112]:
arr12.shape[1]

5

# **selection**

In [118]:
arr13=np.arange(2,20,2)
arr13

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [119]:
arr13==8

array([False, False, False,  True, False, False, False, False, False])

In [120]:
arr13==20

array([False, False, False, False, False, False, False, False, False])

In [122]:
arr13[0:5]<=4

array([ True,  True, False, False, False])

# Filtering

In [123]:
import numpy as np

In [5]:
arr14=np.array([1,2,1010,4,108,10,71,610])
arr14

array([   1,    2, 1010,    4,  108,   10,   71,  610])

In [126]:
arr<80

array([ True,  True, False,  True, False,  True,  True, False])

In [127]:
arr>100

array([False, False,  True, False,  True, False, False,  True])

In [4]:
arr15=np.array([True,False,True,True,False,False,True])
arr15

array([ True, False,  True,  True, False, False,  True])

In [131]:
np.where(arr15) ## find all true elements index

(array([0, 2, 3, 6]),)

In [137]:
np.where(arr14>=10)

(array([2, 4, 5, 6, 7]),)

In [138]:
arr[np.where(arr14>=10)]=10

In [139]:
arr

array([ 1,  2, 10,  4, 10, 10, 10, 10])

In [140]:
np.where(arr==10)

(array([2, 4, 5, 6, 7]),)

In [6]:
arr14.tolist()


[1, 2, 1010, 4, 108, 10, 71, 610]

In [7]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [9]:
np.round(arr14)

array([   1,    2, 1010,    4,  108,   10,   71,  610])

# copy vs view